---
AWSTemplateFormatVersion: 2010-09-09


Description: >
  This template will build distribution and S3 bucket for www to main domain redirection.

Parameters:
  DomainName:
    Type: String
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: >
      Your main domain.
  AcmCertificate:
    Type: String
    AllowedPattern: ^$|(arn:aws:acm:)([a-z0-9/:-])*([a-z0-9])$
    Description: >
      CloudFront Certificate ARN

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub www.${DomainName}
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainName
          Protocol: https

  CloudFrontDistributionSslCertificate:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Sub www.${DomainName}
        Comment: www to main
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          TargetOriginId: s3bucket
          ViewerProtocolPolicy: redirect-to-https
        Origins:
        - DomainName: !Select [2, !Split ["/", !GetAtt S3Bucket.WebsiteURL]]
          Id: s3bucket
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        PriceClass: PriceClass_All
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificate
          SslSupportMethod: sni-only
        Enabled: true